title: jcoleman.engineering

hero_banner_url: https://images.unsplash.com/photo-1497215842964-222b430dc094
hero_banner_title: office
hero_banner_author: Alesia Kazantceva
hero_banner_location: ottawa, canada

highlighter: rouge
