title: jcoleman.engineering

hero_banner_url: https://images.unsplash.com/photo-1535341000823-01aa350a4fbb
hero_banner_title: laptop on desk
hero_banner_author: kevin bhagat
hero_banner_location: Chicago, United States

highlighter: rouge
